### ISSUE TITLE
Add "Select/DeSelect All" to "Pick ★ed Repos to Watch" Dialog

### ISSUE THREAD

**Issue by TPS** [vfeskov/WinABeer#16]
N.B: This replicates https://github.com/vfeskov/WinABeer/issues/11#issuecomment-366518958 per @vfeskov's request of https://github.com/vfeskov/WinABeer/issues/11#issuecomment-366519670:

>What pleasant updates since I last checked!  _Almost_ everything I asked for, but I'd like to request an additional "Select/Unselect All" option to this UI.

**Comment by TPS** [comment]
@vfeskov When does this roll out?  I'd ❤️ to try it! 😀

**Comment by vfeskov** [comment]
in like 8 hours i think, after work

**Comment by vfeskov** [comment]
released it https://github.com/vfeskov/WinABeer/releases/tag/v1.7.0

**Comment by TPS** [comment]
Absolutely ❤️!  Switched completely off Sibbell to your digest version! 🏆 🥂

**Comment by TPS** [comment]
@vfeskov I'm not sure, but possibly some potential optimizations for this:  If I do "Select All," Wa🍺 takes a certain amount of time.  If I close, & then reopen to "Select All" _again_, it seems to take the same amount of time.  That leads me to believe @ least 1 of the following is true:
- [ ] 1.  Wa🍺 _might_ be rechecking all the (even already-WABed) repos to select them again, which seems wasteful
- [ ] 2.  Wa🍺 seems not to employ any client-side (browser-based) caching, which _could_ potentially speed up both ☝️1 & return visits @ later time 

The above optimizations each assume that, once a repo _starts_ having Wa🍺-compatible releases (i.e., those using `/releases`), it doesn't later remove them outright, which seems reasonable — once a repo starts such, it generally will keep it up, & even if doesn't, its owner won't go through to wipe just the _releases_.

**Comment by vfeskov** [comment]
What happens is it sends all not yet selected repos to backend and backend re-checks atom feeds if they have releases

You cannot check atom feeds from browser because of cross-origin restrictions, only using API, which has rate limit, and I wouldn't reuse the same code 

Some optimisation would definitely be cool, but I might even remove restriction to have a release  entirely, because I was told there's a more efficient way of getting release updates

Once I get some free time I'm gonna focus on that
